version: "3.7"

services:
  logdetector-evaluator-flask:
    image: logdetector-evaluator-flask 
    build:
      context: . 
      dockerfile: Dockerfile_flask
    networks:
      - "default"
    ports:
      - 5000:5000

  logdetector-evaluator-falcon:
    image: logdetector-evaluator-falcon 
    build:
      context: . 
      dockerfile: Dockerfile_falcon
    networks:
      - "default"
    ports:
      - 6000:6000

  logdetector-evaluator-fastapi:
    image: logdetector-evaluator-fastapi 
    build:
      context: . 
      dockerfile: Dockerfile_fastapi
    networks:
      - "default"
    ports:
      - 7000:7000

  logdetector-evaluator-japronto:
    image: logdetector-evaluator-japronto 
    build:
      context: . 
      dockerfile: Dockerfile_japronto
    networks:
      - "default"
    ports:
      - 8000:8000

networks:
  default:
    driver: overlay
